### ISSUE TITLE
All 4 examples behave the same way.

### ISSUE THREAD

**Issue by empz** [kentcdodds/react-and-stale-closures#1]
All 4 examples from the [demo](https://react-and-stale-closures.netlify.app/) behave the same. They all update the current active post instead of the one that was active when the heart button was clicked.

**Comment by kentcdodds** [comment]
Just checked and you are mistaken, they are working as described.

**Comment by empz** [comment]
![iuoARYyofp](https://user-images.githubusercontent.com/412489/123646879-e6a79a80-d827-11eb-862b-e3348828ae20.gif)

**Comment by empz** [comment]
Nevermind. I thought this was about displaying the values not about the actual click handler. Clicking the button from a "green tick" example works as expected.
